### ISSUE TITLE
Issues installing plugin in IDA9.1

### ISSUE THREAD

**Issue by greenozon** [w00tzenheimer/d810-ng#5]
I"m not able to bring up this interesting plugin in IDA9.1 GA

steps

```
c:\Prg\>python -V
Python 3.10.17


c:\Prg\>pip3 install z3-solver
Collecting z3-solver
  Downloading z3_solver-4.15.1.0-py3-none-win_amd64.whl.metadata (778 bytes)
Downloading z3_solver-4.15.1.0-py3-none-win_amd64.whl (16.4 MB)
   ---------------------------------------- 16.4/16.4 MB 3.6 MB/s eta 0:00:00
Installing collected packages: z3-solver
Successfully installed z3-solver-4.15.1.0

c:\Prg\>pip3 install z3-solver
Requirement already satisfied: z3-solver in c:\dev\python310\lib\site-packages (4.15.1.0)
```

copied everything from src/  into IDA's  plugin/ dir
when I run IDA is says this:

```
C:\Prg\DA91\plugins\D810.py: module 'typing' has no attribute 'override'
Traceback (most recent call last):
  File "C:\Prg\DA91\python\ida_idaapi.py", line 501, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Prg/DA91/plugins/D810.py", line 168, in <module>
    class Plugin(abc.ABC, idaapi.plugin_t):
  File "C:/Prg/DA91/plugins/D810.py", line 173, in Plugin
    @typing.override
AttributeError: module 'typing' has no attribute 'override'
```

any clues appreciated

**Comment by w00tzenheimer** [comment]
Ah, you're using python 3.10, can you use python 3.12+?

**Comment by greenozon** [comment]
well... 3.10 is not that old, isn't it? :)

also you announced this promise in the readme - 

<img width="563" height="137" alt="Image" src="https://github.com/user-attachments/assets/60323495-6a44-44e6-b66d-e6583a891901" />

**Comment by w00tzenheimer** [comment]
I will update the README Python version and backport to make it work on 3.10 :) will let you know

**Comment by greenozon** [comment]
Hi again!
so I've reinstalled my Python to 3.12.11 and follows the steps in the readme, but still fail....

<img width="963" height="254" alt="Image" src="https://github.com/user-attachments/assets/6434185b-100f-45dc-a6a9-aa61507ac1ee" />

```
C:\Prg\DA91\plugins\D810.py: Traceback (most recent call last):
  File "C:/Prg/DA91/plugins/D810.py", line 393, in PLUGIN_ENTRY
    return D810Plugin()
           ^^^^^^^^^^^^
  File "C:/Prg/DA91/plugins/D810.py", line 313, in __init__
    super().__init__(
  File "C:/Prg/DA91/plugins/D810.py", line 216, in __init__
    self.plugin = self._import_plugin_cls()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Prg/DA91/plugins/D810.py", line 220, in _import_plugin_cls
    mod = importlib.import_module(self.plugin_module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Prg/DA91/plugins\d810\manager.py", line 8, in <module>
    import pyinstrument
ModuleNotFoundError: No module named 'pyinstrument'
```

**Comment by greenozon** [comment]
Hurrey!
latest source from the repo works well now!

PS
Please add into readme as well - installing of this module, otherwise:

```
ModuleNotFoundError: No module named 'pyinstrument'

```

**Comment by greenozon** [comment]
@w00tzenheimer 

new issues :)

I've upgraded my python into 3.12 and having new issues, see below
would be greatful for the hints!

```
c:\Dev\re\ida\d810-ng>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

c:\Dev\re\ida\d810-ng>git pull
Already up to date.

c:\Dev\re\ida\d810-ng>git remote -v
origin  https://github.com/w00tzenheimer/d810-ng.git (fetch)
origin  https://github.com/w00tzenheimer/d810-ng.git (push)


c:\Dev\re\ida\d810-ng>pip3 freeze
pyinstrument==5.0.3
typing_extensions==4.14.1
z3-solver==4.15.1.0

c:\Dev\re\ida\d810-ng>python -V
Python 3.12.11

c:\Dev\re\ida\d810-ng>pip3 freeze
pyinstrument==5.0.3
typing_extensions==4.14.1
z3-solver==4.15.1.0
```


from Ida9.1  -


```
C:\Prg\DA91\plugins\D810.py: Traceback (most recent call last):
  File "C:/Prg/DA91/plugins/D810.py", line 794, in PLUGIN_ENTRY
    return D810Plugin()
           ^^^^^^^^^^^^
  File "C:/Prg/DA91/plugins/D810.py", line 730, in __init__
    super().__init__(
  File "C:/Prg/DA91/plugins/D810.py", line 646, in __init__
    self.plugin = self._import_plugin_cls()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Prg/DA91/plugins/D810.py", line 650, in _import_plugin_cls
    mod = importlib.import_module(self.plugin_module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Prg/DA91/plugins\d810\manager.py", line 12, in <module>
    from d810.hexrays.hexrays_hooks import (
  File "C:\Prg/DA91/plugins\d810\hexrays\hexrays_hooks.py", line 13, in <module>
    from d810.expr.z3_utils import log_z3_instructions
  File "C:\Prg/DA91/plugins\d810\expr\z3_utils.py", line 16, in <module>
    import z3
  File "C:\dev\Python312\Lib\site-packages\z3\__init__.py", line 1, in <module>
    from .z3 import *
  File "C:\dev\Python312\Lib\site-packages\z3\z3.py", line 46, in <module>
    from . import z3core
  File "C:\dev\Python312\Lib\site-packages\z3\z3core.py", line 119, in <module>
    _lib.Z3_solver_register_on_clause.restype = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Python312\Lib\ctypes\__init__.py", line 392, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\Python312\Lib\ctypes\__init__.py", line 397, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function 'Z3_solver_register_on_clause' not found
```

**Comment by greenozon** [comment]
Thanks a lot!
you won't belive  but...
clearing the cache file did not help!!!

bada-boom :)


After some looking around figured out my very special case!
for some reason I had an older version of libz3.dll in ida dir.... -> very very big trouble as above :)

Export: 738 (old)  vs 785 (required one)
libz3.dll   17 MB


leaving ref link for those who'll hit simlar tricky case in the future - 

https://github.com/Z3Prover/z3/issues/2352
